#!/bin/bash

set -e  # Exit immediately if a command exits with a non-zero status.

# Define the absolute path to your project directory
PROJECT_DIR="/Users/spencerthayer/Documents/Work/Election-Polling"
VENV_DIR="$PROJECT_DIR/venv"
REQUIREMENTS_FILE="$PROJECT_DIR/requirements.txt"
PYTHON_SCRIPT="$PROJECT_DIR/analysis.py"

echo "Activating virtual environment..."
source $VENV_DIR/bin/activate

# Run the Python script
echo "Running the Python script..."
python $PYTHON_SCRIPT

# python /Users/spencerthayer/Documents/Work/Election-Polling/analysis.py

# Deactivate the virtual environment
deactivate
echo "Virtual environment deactivated."